spring.application.name=projeto-lds-2026

spring.datasource.name=elixozero
spring.datasource.base.url=jdbc:postgres://localhost:5432
spring.datasource.url=jdbc:postgresql://localhost:5432/${spring.datasource.name}
spring.datasource.username=postgres
spring.datasource.password=Chico-2019
